site_url: https://olivier-roger-vet.github.io/veille-reglementaire
use_directory_urls: false
site_name: Veille réglementaire
site_description: actualités réglementaires en santé animale, santé publique et hygiène alimentaire
site_author: Olivier ROGER

nav:
  - Historique: index.md
  - Eau: eau.md
  - Hygiène alimentaire: hygiene_alimentaire.md
  - Lait: lait.md
  - Santé animale: sante_animale.md
  #- showroom: showroom.md

theme:
  name: material
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.path
    # - navigation.footer
    # - navigation.indexes # not compatible with toc.integrate
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # not compatible with navigation.indexes
  icon:
    logo: octicons/law-24
    annotation: material/plus-circle-outline

plugins:
  #- search
  - tags
extra:
  tags:
    Takeaway: takeaway
  # social:
  #  - icon: simple/linkedin
  #    link: https://www.linkedin.com/in/olivier-roger-dev
  #    name: See my profile
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  generator: false
copyright: 16/10/2025 &copy; Olivier ROGER
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
watch:
  # when the glossary file is updated, the project is automatically reloaded when running mkdocs serve.
  - includes
extra_css:
  - stylesheets/extra.css